// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: api.proto

package notifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierClient interface {
	EnqueueNotificationEvent(ctx context.Context, in *EnqueueNotificationEventReq, opts ...grpc.CallOption) (*EnqueueNotificationEventRes, error)
	StreamNotificationEvents(ctx context.Context, in *StreamNotificationEventsReq, opts ...grpc.CallOption) (Notifier_StreamNotificationEventsClient, error)
}

type notifierClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierClient(cc grpc.ClientConnInterface) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) EnqueueNotificationEvent(ctx context.Context, in *EnqueueNotificationEventReq, opts ...grpc.CallOption) (*EnqueueNotificationEventRes, error) {
	out := new(EnqueueNotificationEventRes)
	err := c.cc.Invoke(ctx, "/notifier.Notifier/EnqueueNotificationEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) StreamNotificationEvents(ctx context.Context, in *StreamNotificationEventsReq, opts ...grpc.CallOption) (Notifier_StreamNotificationEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Notifier_ServiceDesc.Streams[0], "/notifier.Notifier/StreamNotificationEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &notifierStreamNotificationEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Notifier_StreamNotificationEventsClient interface {
	Recv() (*StreamNotificationEventsRes, error)
	grpc.ClientStream
}

type notifierStreamNotificationEventsClient struct {
	grpc.ClientStream
}

func (x *notifierStreamNotificationEventsClient) Recv() (*StreamNotificationEventsRes, error) {
	m := new(StreamNotificationEventsRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotifierServer is the server API for Notifier service.
// All implementations must embed UnimplementedNotifierServer
// for forward compatibility
type NotifierServer interface {
	EnqueueNotificationEvent(context.Context, *EnqueueNotificationEventReq) (*EnqueueNotificationEventRes, error)
	StreamNotificationEvents(*StreamNotificationEventsReq, Notifier_StreamNotificationEventsServer) error
	mustEmbedUnimplementedNotifierServer()
}

// UnimplementedNotifierServer must be embedded to have forward compatible implementations.
type UnimplementedNotifierServer struct {
}

func (UnimplementedNotifierServer) EnqueueNotificationEvent(context.Context, *EnqueueNotificationEventReq) (*EnqueueNotificationEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueNotificationEvent not implemented")
}
func (UnimplementedNotifierServer) StreamNotificationEvents(*StreamNotificationEventsReq, Notifier_StreamNotificationEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNotificationEvents not implemented")
}
func (UnimplementedNotifierServer) mustEmbedUnimplementedNotifierServer() {}

// UnsafeNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServer will
// result in compilation errors.
type UnsafeNotifierServer interface {
	mustEmbedUnimplementedNotifierServer()
}

func RegisterNotifierServer(s grpc.ServiceRegistrar, srv NotifierServer) {
	s.RegisterService(&Notifier_ServiceDesc, srv)
}

func _Notifier_EnqueueNotificationEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueNotificationEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).EnqueueNotificationEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifier.Notifier/EnqueueNotificationEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).EnqueueNotificationEvent(ctx, req.(*EnqueueNotificationEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_StreamNotificationEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNotificationEventsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotifierServer).StreamNotificationEvents(m, &notifierStreamNotificationEventsServer{stream})
}

type Notifier_StreamNotificationEventsServer interface {
	Send(*StreamNotificationEventsRes) error
	grpc.ServerStream
}

type notifierStreamNotificationEventsServer struct {
	grpc.ServerStream
}

func (x *notifierStreamNotificationEventsServer) Send(m *StreamNotificationEventsRes) error {
	return x.ServerStream.SendMsg(m)
}

// Notifier_ServiceDesc is the grpc.ServiceDesc for Notifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifier.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueNotificationEvent",
			Handler:    _Notifier_EnqueueNotificationEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNotificationEvents",
			Handler:       _Notifier_StreamNotificationEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
